mysite2/core/urls.py
from django.urls import path
from. import views

app_name = 'core'

urlpatterns = [
    path('',views.index, name='index')
]

mysite2/isi/urls.py
from django.urls import path
from. import views

app_name = 'isi'

urlpatterns = [
    path('isiberita/',views.isi, name='isi berita'),
]

mysite2/mysite2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('core.urls')),
    path('', include('news.urls')),
    path('', include('isi.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite2/news/urls.py
from django.urls import path
from. import views

app_name = 'news'

urlpatterns = [
    path('all/',views.all, name='all'),
    path('trending/',views.trending, name='trending'),
    path('sport/', views.sport, name='sport'),
    path('politics/', views.politics, name='politics'),
    path('lifestyle/', views.lifestyle, name='lifestyle'),
    path('healty/', views.healty, name='healty'),
    path('entartaiment/', views.entartaiment, name='entartaiment'),
    path('isi/<int:id>',views.isi, name='isi'),

]

mysite2/core/models.py
from django.db import models

# Create your models here.

mysite2/isi/models.py
from django.db import models

# Create your models here.

mysite2/news/models.py
from django.db import models
from mysite2 import settings
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager,PermissionsMixin

# Create your models here.
class CustomuserManager(BaseUserManager):
    def _create_user(self,email,name,phone,is_admin,is_staff,is_active,status,password,**extra_fields):
        if not email :\
            raise ValueError("The email field must be set")

        email = self.normalize_email(email)
        user = self.model(email=email, name=name, phone=phone, is_admin=is_admin, is_staff=is_staff, is_active=is_active, password=password,**extra_fields) 
        user.set_password(password)
        user.save(using=self.db)

        return user

    def create_user(self, email, name, phone, is_admin, is_status, is_staff, is_active, status, password = None, **extra_fields):
        return self._create_user(email, name, phone, status, is_admin, is_staff, True, password, **extra_fields)

    def create_superuser(self, email, name, phone, is_admin, is_staff, is_active, status, password = None, **extra_fields):
        return self._create_user(email, name, phone, True, True, True, 'admin', password, **extra_fields, is_superuser = True)       

class Customuser(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    phone = models.CharField(max_length=255, blank=True, null=True)
    is_admin = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    status_list = {
        ('admin','admin'),
        ('user','user')
    } 
    password = models.CharField(max_length=255)


    status = models.CharField(max_length=255, choices=status_list, blank=True, null=True, default='admin')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'password','phone', 'status','is_admin', 'is_staff', 'is_active']

    object = CustomuserManager()

    def __str__(self) :
        return '{}|{}'.format(self.name, self.email)

    


class kategori(models.Model):
        namaKategori =models.CharField(max_length=255)

        def __str__(self):
             return self.namaKategori

class berita(models.Model):
    STATUS = ('publish', 'publish'),('draft', 'draft')

    judul = models.CharField(max_length=255)
    isi = models.CharField(max_length=999)
    kategori =models.ForeignKey(kategori,on_delete=models.CASCADE)
    kategoriID = models.IntegerField(max_length=255)
    gambar =models.ImageField(upload_to='media', height_field=None,width_field=None,max_length=100)
    penulis = models.CharField(max_length=255)
    status = models.CharField(choices=STATUS, max_length=200)
    

mysite2/core/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'core/index.html')

mysite2/isi/views.py
from django.shortcuts import render

# Create your views here.
def isi(request):
    return render(request, "berita/isiberita.html")

mysite2/news/views.py
from django.shortcuts import render, get_object_or_404
from . import models

# Create your views here.
def all(request):
    if 'cari' in request.GET:
        cari = request.GET['cari']
        berita = models.berita.objects.filter(judul__icontains=cari) 
    else:
        berita = models.berita.objects.all()
    context = {'beritas' : berita}
    return render(request, 'menu/all.html', context)

def isi (request,id):
    berita = get_object_or_404(models.berita,pk=id)
    context = {'beritas' : berita}
    return render(request, "menu/isiberita.html", context)

def trending(request):
    berita = models.berita.objects.filter(status='publish')
    kategori = models.kategori.objects.all()
    catID = 1
    if catID :
        berita = models.berita.objects.filter(kategori = catID)
    else :
        berita = models.berita.objects.filter(status = 'publish')
    
    context = {'beritas' : berita, 'kategori' : kategori}

    return render(request, 'menu/trending.html', context)

def sport(request):
    berita = models.berita.objects.filter(status='publish')
    kategori = models.kategori.objects.all()
    catID = 2
    if catID :
        berita = models.berita.objects.filter(kategori = catID)
    else :
        berita = models.berita.objects.filter(status = 'publish')
    
    context = {'beritas' : berita, 'kategori' : kategori}

    return render(request, 'menu/sport.html', context)

def politics(request):
    berita = models.berita.objects.filter(status='publish')
    kategori = models.kategori.objects.all()
    catID = 3
    if catID :
        berita = models.berita.objects.filter(kategori = catID)
    else :
        berita = models.berita.objects.filter(status = 'publish')
    
    context = {'beritas' : berita, 'kategori' : kategori}

    return render(request, 'menu/politics.html', context)

def lifestyle(request):
    berita = models.berita.objects.filter(status='publish')
    kategori = models.kategori.objects.all()
    catID = 4
    if catID :
        berita = models.berita.objects.filter(kategori = catID)
    else :
        berita = models.berita.objects.filter(status = 'publish')
    
    context = {'beritas' : berita, 'kategori' : kategori}

    return render(request, 'menu/lifestyle.html', context)

def healty(request):
    berita = models.berita.objects.filter(status='publish')
    kategori = models.kategori.objects.all()
    catID = 5
    if catID :
        berita = models.berita.objects.filter(kategori = catID)
    else :
        berita = models.berita.objects.filter(status = 'publish')
    
    context = {'beritas' : berita, 'kategori' : kategori}

    return render(request, 'menu/healty.html', context)

def entartaiment(request):
    berita = models.berita.objects.filter(status='publish')
    kategori = models.kategori.objects.all()
    catID = 6
    if catID :
        berita = models.berita.objects.filter(kategori = catID)
    else :
        berita = models.berita.objects.filter(status = 'publish')
    
    context = {'beritas' : berita, 'kategori' : kategori}

    return render(request, 'menu/entartaiment.html', context)

mysite2/core/templates/core/base.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title%}{% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    {% block htmlhead %} {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-danger">
      <div class="container-fluid">
        <a class="navbar-brand text-white fw-bold" href="#">EduNews</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/all">All</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/trending">Trending</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/sport">Sport</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/politics">Politics</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/lifestyle">Lifestyle</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/healty">Healty</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/entartaiment">Entartaiment</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/isiberita">Isiberita</a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Dropdown
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="#">Something else here</a>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

mysite2/news/templates/menu/all.html
{% extends 'core/base.html' %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  {% block htmlhead %}
  {% load static %}
  <link rel="stylesheet type="text css" href="{% static 'index.css' %"}>
  {% endblock htmlhead %}
  </head>
<body>
    {% block content %}
    <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" data-bs-interval="10000">
            <img src="https://i.pinimg.com/564x/5c/c9/e1/5cc9e18012db75db377a31a9a60195ec.jpg" class="d-block w-89" alt="...">
          </div>
          <div class="carousel-item" data-bs-interval="2000">
            <img src="https://i.pinimg.com/564x/18/bf/6a/18bf6aa35c84c044131f617e1813105c.jpg" class="d-block w-98" alt="...">
          </div>
          <div class="carousel-item">
            <img src="https://i.pinimg.com/564x/fa/8c/5b/fa8c5b53934fb88a193687ed2a5e07f7.jpg" class="d-block w-98" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>

      <a class="weatherwidget-io" href="https://forecast7.com/en/n6d92107d62/bandung/" data-label_1="BANDUNG" data-label_2="WEATHER" data-theme="gray" >BANDUNG WEATHER</a>
      <br><br><br>
      <script>
      !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
      </script>
      <div class="container text-center">
        <div class="row">
          <div class="col">
            <br><br><br>
            <nav class="navbar bg-body-tertiary" style="right: -500px;">
              <div class="container-fluid">
                <form class="d-flex" role="search">
                  <input class="form-control me-2" name="cari" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </nav>
            <H1>BTS</H1>
            <img src="https://www.blibli.com/friends-backend/wp-content/uploads/2021/08/lagu-bts.jpg" alt="">
          </div>
        </div>
      </div>
          <div class="col">
            <P>BTS (Korean: 방탄소년단; RR: Bangtan Sonyeondan; lit. Bulletproof Boy Scouts), also known as the Bangtan Boys, is a South Korean boy band formed in 2010. The band consists of Jin, Suga, J-Hope, RM, Jimin, V, and Jungkook, who co-write or co-produce much of their material. Originally a hip hop group, they expanded their musical style to incorporate a wide range of genres, while their lyrics have focused on subjects including mental health, the troubles of school-age youth and coming of age, loss, the journey towards self-love, individualism, and the consequences of fame and recognition.</P>
          </div>
  
          
          <div class="container text-center">
            <div class="row">
                {% for Berita in beritas %}
              <div class="col">
                <div class="card" style="width: 18rem;">
                    <img src="{{Berita.gambar.url}}"lt="...">
                    <br><br><br>
                    <div class="card-body">
                      <h5 class="card-title">{{Berita.judul}}</h5>
                      <p class="card-text">{{Berita.isi}}</p>
                      <button type="button" class="btn btn-danger btn-sm" onclick="location.href='isiberita'"><a href="{% url 'news:isi' Berita.id %}" style="text-decoration:none ;">click here</a></button>

                    </div>
                  </div>
              </div>
              {% endfor %}
                  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
                  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
                  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
                  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
                      
                          </button>
                        </div>
                  
                      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
                      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
                      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
                        <!-- Site footer -->
                        <footer class="site-footer" style="background-color: slategrey;">
                          <div class="container">
                            <div class="row">
                              <div class="col-sm-12 col-md-6">
                                <h6>About</h6>
                                <p class="text-justify">Scanfcode.com <i>CODE WANTS TO BE SIMPLE </i> is an initiative  to help the upcoming programmers with the code. Scanfcode focuses on providing the most efficient code or snippets as the code wants to be simple. We will help programmers build up concepts in different programming languages that include C, C++, Java, HTML, CSS, Bootstrap, JavaScript, PHP, Android, SQL and Algorithm.</p>
                              </div>
                    
                              <div class="col-xs-6 col-md-3">
                                <h6>Categories</h6>
                                <ul class="footer-links">
                                  <li><a href="http://scanfcode.com/category/c-language/">C</a></li>
                                  <li><a href="http://scanfcode.com/category/front-end-development/">UI Design</a></li>
                                  <li><a href="http://scanfcode.com/category/back-end-development/">PHP</a></li>
                                  <li><a href="http://scanfcode.com/category/java-programming-language/">Java</a></li>
                                  <li><a href="http://scanfcode.com/category/android/">Android</a></li>
                                  <li><a href="http://scanfcode.com/category/templates/">Templates</a></li>
                                </ul>
                              </div>
                    
                              <div class="col-xs-6 col-md-3">
                                <h6>Quick Links</h6>
                                <ul class="footer-links">
                                  <li><a href="http://scanfcode.com/about/">About Us</a></li>
                                  <li><a href="http://scanfcode.com/contact/">Contact Us</a></li>
                                  <li><a href="http://scanfcode.com/contribute-at-scanfcode/">Contribute</a></li>
                                  <li><a href="http://scanfcode.com/privacy-policy/">Privacy Policy</a></li>
                                  <li><a href="http://scanfcode.com/sitemap/">Sitemap</a></li>
                                </ul>
                              </div>
                            </div>
                            <hr>
                          </div>
                          <div class="container">
                            <div class="row">
                              <div class="col-md-8 col-sm-6 col-xs-12">
                                <p class="copyright-text">Copyright &copy; 2017 All Rights Reserved by 
                             <a href="#">Scanfcode</a>.
                                </p>
                              </div>
                    
                              <div class="col-md-4 col-sm-6 col-xs-12">
                                <ul class="social-icons">
                                  <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                                  <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                                  <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
                                  <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>  
            </div>
          </div>
      </div>
  </div>
  {% endblock %}
</body>
</html>

mysite2/news/templates/menu/entartaiment.html
{% extends 'core/base.html' %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}lifestyle{% endblock %}</title>
    {% block htmlhead %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    {% endblock htmlhead %}
  </head>
  <body>
    {% block content %}
    <div id="carouselExample" class="carousel slide">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="https://asset-2.tstatic.net/tribunnewswiki/foto/bank/images/Serial-My-Nerd-Girl.jpg" class="d-block w-100" alt="...">
          </div>
          <div style="text-align: center; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
            <h1 style="color: rgb(0, 0, 0); font-size: 340%; text-shadow: 3px 2px 1px grey;">Naura dan Devano</h1>
            <button type="button" class="btn btn-success">click here</button>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <a class="weatherwidget-io" href="https://forecast7.com/en/n6d92107d62/bandung/" data-label_1="BANDUNG" data-label_2="WEATHER" data-theme="metallic" >BANDUNG WEATHER</a>
      <br><br><br>
      <h1>New Article</h1>
      <br><br>
      <div class="container text-center">
        <div class="row">
            {% for Berita in beritas %}
          <div class="col">
            <div class="card" style="width: 18rem;">
                <img src="{{Berita.gambar.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h6 style="color:black;">{{Berita.kategori}}</h6>
                  <h5 style="color:red;margin-top: 20px;">{{Berita.judul}}</h5>
                  <h4 class="card-text" style="margin-top: 20px;">{{Berita.deskripsi}}</h4>
                  <p class="card-text">{{Berita.isi}}</p>
                  <p style="font-size:small ; color: rgba(134, 134, 134, 134); text-align: left; margin-top: 30px;">{{Berita.penulis}}, {{Berita.publikasi}}</p>
                  <button type="button" class="btn btn-primary"> <a href="{% url 'news:isi' Berita.id %}">go to site</a></button>
                </div>
              </div>
          </div>
        {% endfor %}
    </div>
  </div>
<script>
  
!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
</script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
      <!-- Site footer -->
      <footer class="site-footer">
        <div class="container">
          <div class="row">
            <div class="col-sm-12 col-md-6">
              <h6>About</h6>
              <p class="text-justify">Scanfcode.com <i>CODE WANTS TO BE SIMPLE </i> is an initiative  to help the upcoming programmers with the code. Scanfcode focuses on providing the most efficient code or snippets as the code wants to be simple. We will help programmers build up concepts in different programming languages that include C, C++, Java, HTML, CSS, Bootstrap, JavaScript, PHP, Android, SQL and Algorithm.</p>
            </div>
  
            <div class="col-xs-6 col-md-3">
              <h6>Categories</h6>
              <ul class="footer-links">
                <li><a href="http://scanfcode.com/category/c-language/">C</a></li>
                <li><a href="http://scanfcode.com/category/front-end-development/">UI Design</a></li>
                <li><a href="http://scanfcode.com/category/back-end-development/">PHP</a></li>
                <li><a href="http://scanfcode.com/category/java-programming-language/">Java</a></li>
                <li><a href="http://scanfcode.com/category/android/">Android</a></li>
                <li><a href="http://scanfcode.com/category/templates/">Templates</a></li>
              </ul>
            </div>
  
            <div class="col-xs-6 col-md-3">
              <h6>Quick Links</h6>
              <ul class="footer-links">
                <li><a href="http://scanfcode.com/about/">About Us</a></li>
                <li><a href="http://scanfcode.com/contact/">Contact Us</a></li>
                <li><a href="http://scanfcode.com/contribute-at-scanfcode/">Contribute</a></li>
                <li><a href="http://scanfcode.com/privacy-policy/">Privacy Policy</a></li>
                <li><a href="http://scanfcode.com/sitemap/">Sitemap</a></li>
              </ul>
            </div>
          </div>
          <hr>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
              <p class="copyright-text">Copyright &copy; 2017 All Rights Reserved by 
           <a href="#">Scanfcode</a>.
              </p>
            </div>
  
            <div class="col-md-4 col-sm-6 col-xs-12">
              <ul class="social-icons">
                <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
                <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>   
              </ul>
            </div>
          </div>
        </div>
  </footer>
    {% endblock %}
  </body>
</html>